#!/bin/bash
# Usage: ./Taskfile <fname>

function mpdetector {
    type='video'
    path=''

    if [[ $# -eq 0 ]]; then
        type='static'
        path='/home/robbedec/repos/ugent/thesis-inwe/data/MEEI_Standard_Set/Flaccid/MildFlaccid/MildFlaccid1/MildFlaccid1_1.jpg'
    else
        path="$1"
    fi

    python3 src/keypoints/detectors/MediapipeKPDetector.py \
        -i "${path}"
        -t "${type}"
}

function threshold {
    echo ""
}

function static_analyzer {
    echo ""
}

function video_analyzer {
    echo ""
}

function create_recording {
    python3 src/samples/videocapture.py \
        -p "/home/robbedec/repos/ugent/thesis-inwe/videos" \
        -n "test.avi"
}

"$@"